const canvas=document.getElementById('gameCanvas'); const ctx=canvas.getContext('2d');
const upgradeVideo=document.getElementById('upgradeVideo');
const healthFrameImage=new Image();
healthFrameImage.src='assets/hud_health_frame.png';
const skillFrameImage=new Image();
skillFrameImage.src='assets/hud_skill_frame.png';
const dashFrameImage=new Image();
dashFrameImage.src='assets/hud_dash_frame.png';
const coinImage=new Image();
coinImage.src='assets/coin_pickup.png';
const healthPackImage=new Image();
healthPackImage.src='assets/health_pack.png';
const portalImage=new Image();
portalImage.src='assets/portal.png';
const streetBgs=['assets/street_bg_1.png','assets/street_bg_2.png','assets/street_bg_3.png','assets/street_bg_4.png','assets/street_bg_5.png'].map(src=>{
  const img=new Image();
  img.src=src;
  return img;
});
const cutsceneImages=['assets/cutscene_1.png','assets/cutscene_2.png','assets/cutscene_3.png','assets/cutscene_4.png'].map(src=>{
  const img=new Image();
  img.src=src;
  return img;
});
const bossCutsceneImages=['assets/boss_cutscene_1.png','assets/boss_cutscene_2.png'].map(src=>{
  const img=new Image();
  img.src=src;
  return img;
});
const titleVideo=document.getElementById('titleVideo');
const titleMusic=document.getElementById('titleMusic');
const cutsceneMusic=document.getElementById('cutsceneMusic');
const mapMusic=document.getElementById('mapMusic');
const bossMusic=document.getElementById('bossMusic');
const smGamesLogoImage=new Image();
smGamesLogoImage.src='assets/sm_games_logo.png';
const playerSpriteSheet=new Image();
playerSpriteSheet.src='assets/spritesheet.png';
const playerJumpSpriteSheet=new Image();
playerJumpSpriteSheet.src='assets/spritesheet_jump.png';
const playerPunch1SpriteSheet=new Image();
playerPunch1SpriteSheet.src='assets/spritesheet_punch1.png';
const playerPunch2SpriteSheet=new Image();
playerPunch2SpriteSheet.src='assets/spritesheet_punch2.png';
const playerWalkSpriteSheet=new Image();
playerWalkSpriteSheet.src='assets/spritesheet_walk.png';
const playerSkillSpriteSheet=new Image();
playerSkillSpriteSheet.src='assets/spritesheet_skill.png';
const playerDashSpriteSheet=new Image();
playerDashSpriteSheet.src='assets/spritesheet_dash.png';
const playerHitSpriteSheet=new Image();
playerHitSpriteSheet.src='assets/spritesheet_hit.png';
const playerDeathSpriteSheet=new Image();
playerDeathSpriteSheet.src='assets/spritesheet_death.png';
const playerClimbSpriteSheet=new Image();
playerClimbSpriteSheet.src='assets/spritesheet_climb.png';
const enemyBatDeathSpriteSheet=new Image();
enemyBatDeathSpriteSheet.src='assets/enemy_bat_death.png';
const enemyBatAttackSpriteSheet=new Image();
enemyBatAttackSpriteSheet.src='assets/enemy_bat_attack.png';
const enemyBatWalkSpriteSheet=new Image();
enemyBatWalkSpriteSheet.src='assets/enemy_bat_walk.png';
const enemyWomanAttackSpriteSheet=new Image();
enemyWomanAttackSpriteSheet.src='assets/enemy_woman_attack.png';
const enemyWomanDeathSpriteSheet=new Image();
enemyWomanDeathSpriteSheet.src='assets/enemy_woman_death.png';
const enemyWomanWalkSpriteSheet=new Image();
enemyWomanWalkSpriteSheet.src='assets/enemy_woman_walk.png';
const enemyOldmanWalkSpriteSheet=new Image();
enemyOldmanWalkSpriteSheet.src='assets/enemy_oldman_walk.png';
const enemyOldmanCombatSpriteSheet=new Image();
enemyOldmanCombatSpriteSheet.src='assets/enemy_oldman_combat.png';
const enemyBottleSpriteSheet=new Image();
enemyBottleSpriteSheet.src='assets/enemy_bottle_attack.png';
const bossWalkSpriteSheet=new Image();
bossWalkSpriteSheet.src='assets/boss_walk.png';
const bossMeleeSpriteSheet=new Image();
bossMeleeSpriteSheet.src='assets/boss_melee.png';
const bossRangedSpriteSheet=new Image();
bossRangedSpriteSheet.src='assets/boss_ranged.png';
const bossChargeSpriteSheet=new Image();
bossChargeSpriteSheet.src='assets/boss_charge.png';
const crateSpriteSheet=new Image();
crateSpriteSheet.src='assets/crate.png';

